{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue-Bold;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab560
\pard\pardeftab560\slleading20\pardirnatural\partightenfactor0

\f0\b\fs26 \cf0 ---\
- name: Uncork Take Home\
  hosts: localhost\
  tasks:\
    - name: Create a New Namespace\
      command: kubectl create namespace steve-test  \
      ignore_errors: yes\
      register: create_namespace_result\
\
    - name: Check if Namespace Already Exists\
      set_fact:\
        namespace_already_exists: "\{\{ create_namespace_result.rc == 0 \}\}"\
\
    - name: Print Status\
      debug:\
        msg: |\
          Namespace '\{\{ steve-test  if not namespace_already_exists else 'already exists' \}\}'\
      when: create_namespace_result.rc != 0\
\
    - name: Fail if Namespace Creation Failed\
      fail:\
        msg: "Failed to create the namespace steve-test ."\
      when: create_namespace_result.rc != 0}